#!/usr/bin/env bash
set -Eeuo pipefail

# Realityscanner installer (VPS + OpenWrt artifacts)
# Supported: Ubuntu/Debian with systemd, run as root.

umask 077

usage() {
  cat >&2 <<'EOF'
Usage:
  sudo bash install.sh

Non-interactive (for tests/sandbox):
  bash install.sh --non-interactive \
    --project-root <path> \
    --env-file <path> \
    --systemd-dir <path> \
    --out-dir <path> \
    --skip-systemd-enable \
    --marzban-url <url> \
    --xray-inbound-tag <tag> \
    --state-dir <path> \
    --marzban-user <user> \
    --marzban-pass <pass> \
    --sub-url <url>
EOF
}

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd -P)"

NON_INTERACTIVE=0
SKIP_SYSTEMD_ENABLE=0

PROJECT_ROOT=""
STATE_DIR=""
ENV_FILE="/etc/reality-autorotate.env"
SYSTEMD_DIR="/etc/systemd/system"
OUT_DIR=""
SYSTEMCTL_BIN="systemctl"

MARZBAN_URL=""
XRAY_INBOUND_TAG=""
MARZBAN_USER=""
MARZBAN_PASS=""
TG_TOKEN=""
TG_ID=""
SUB_URL=""

# Helpers
require_nonempty() {
  local name="$1" value="$2"
  if [[ -z "$value" ]]; then
    echo "ERROR: missing required: $name" >&2
    return 1
  fi
  return 0
}

validate_state_dir() {
  local dir="$1"
  dir="${dir%%$'\r'}"
  dir="${dir%%$'\n'}"
  if [[ "$dir" != "/" ]]; then
    dir="${dir%/}"
  fi
  if [[ -z "$dir" || "$dir" == "/" || "$dir" != /* ]]; then
    echo "ERROR: invalid STATE_DIR: $dir" >&2
    return 1
  fi
  return 0
}

write_env_file() {
  local path="$1"
  mkdir -p "$(dirname -- "$path")"

  # Overwrite is ok in non-interactive mode; interactive will confirm separately.
  cat >"$path" <<EOF
# Generated by realityscanner install.sh

# Marzban
MARZBAN_URL="${MARZBAN_URL}"
MARZBAN_USER="${MARZBAN_USER}"
MARZBAN_PASS="${MARZBAN_PASS}"
XRAY_INBOUND_TAG="${XRAY_INBOUND_TAG}"

# Paths
PROJECT_ROOT="${PROJECT_ROOT}"

# State
STATE_DIR="${STATE_DIR}"

# Rotate
DEST_FAIL_COUNT=5
ROTATE_COOLDOWN=300
VERIFY_TIMEOUT=5

# Scanner
SCANNER_MODE="offline"

# scan_pick pipeline logging
SCAN_PICK_LOG_MAX_BYTES=1048576
SCAN_PICK_LOG_KEEP=5

# Telegram (optional)
TG_TOKEN="${TG_TOKEN}"
TG_ID="${TG_ID}"
EOF

  chmod 600 "$path" 2>/dev/null || true
}

copy_units() {
  local dst="$1"
  mkdir -p "$dst"

  local src_dir="$PROJECT_ROOT/autorotate/systemd"
  if [[ ! -d "$src_dir" ]]; then
    echo "ERROR: systemd units dir not found: $src_dir" >&2
    return 1
  fi

  cp -f -- "$src_dir/reality-autorotate-rotate.service" "$dst/"
  cp -f -- "$src_dir/reality-autorotate-watchdog.service" "$dst/"
  cp -f -- "$src_dir/reality-autorotate-watchdog.timer" "$dst/"
}

generate_openwrt_out() {
  local out="$1"
  mkdir -p "$out/openwrt"

  local src_sh="$PROJECT_ROOT/autorotate/openwrt/podkop-sub-sync.sh"
  if [[ ! -f "$src_sh" ]]; then
    echo "ERROR: OpenWrt script not found: $src_sh" >&2
    return 1
  fi

  cp -f -- "$src_sh" "$out/openwrt/podkop-sub-sync.sh"
  chmod 0755 "$out/openwrt/podkop-sub-sync.sh" 2>/dev/null || true

  if [[ -n "$SUB_URL" ]]; then
    cat >"$out/openwrt/podkop-sub-sync.conf" <<EOF
# Generated by realityscanner install.sh
SUB_URL="${SUB_URL}"
EOF
    chmod 0600 "$out/openwrt/podkop-sub-sync.conf" 2>/dev/null || true
  else
    # Still generate a template to guide user.
    cat >"$out/openwrt/podkop-sub-sync.conf" <<'EOF'
# Generated by realityscanner install.sh
# Fill in your subscription URL:
SUB_URL="https://sub.example.com/sub/REPLACE_ME"
EOF
    chmod 0600 "$out/openwrt/podkop-sub-sync.conf" 2>/dev/null || true
  fi

  cat >"$out/openwrt/INSTALL_OPENWRT.txt" <<'EOF'
OpenWrt install (no SSH required)

You need to place two files on your router:

1) Script:
   - path: /usr/bin/podkop-sub-sync.sh
   - permissions: executable (chmod +x)

2) Config:
   - path: /etc/podkop-sub-sync.conf
   - permissions: 600 (chmod 600)

Then add cron (run every minute):
  * * * * * /usr/bin/podkop-sub-sync.sh >/dev/null 2>&1

Verify:
  /usr/bin/podkop-sub-sync.sh
  uci -q get podkop.main.proxy_string
  logread | grep -F podkop-sub-sync | tail -n 50

Notes:
- The script will NOT log vless:// contents.
- It applies changes only if the link changed.
EOF
}

# Arg parsing
while [[ $# -gt 0 ]]; do
  case "$1" in
    -h|--help)
      usage
      exit 0
      ;;
    --non-interactive)
      NON_INTERACTIVE=1
      shift
      ;;
    --skip-systemd-enable)
      SKIP_SYSTEMD_ENABLE=1
      shift
      ;;
    --project-root)
      PROJECT_ROOT="${2:-}"; shift 2 ;;
    --state-dir)
      STATE_DIR="${2:-}"; shift 2 ;;
    --env-file)
      ENV_FILE="${2:-}"; shift 2 ;;
    --systemd-dir)
      SYSTEMD_DIR="${2:-}"; shift 2 ;;
    --out-dir)
      OUT_DIR="${2:-}"; shift 2 ;;
    --systemctl-bin)
      SYSTEMCTL_BIN="${2:-}"; shift 2 ;;

    --marzban-url)
      MARZBAN_URL="${2:-}"; shift 2 ;;
    --xray-inbound-tag)
      XRAY_INBOUND_TAG="${2:-}"; shift 2 ;;
    --marzban-user)
      MARZBAN_USER="${2:-}"; shift 2 ;;
    --marzban-pass)
      MARZBAN_PASS="${2:-}"; shift 2 ;;
    --tg-token)
      TG_TOKEN="${2:-}"; shift 2 ;;
    --tg-id)
      TG_ID="${2:-}"; shift 2 ;;
    --sub-url)
      SUB_URL="${2:-}"; shift 2 ;;

    *)
      echo "ERROR: unknown argument: $1" >&2
      usage
      exit 2
      ;;
  esac
 done

# Defaults
if [[ -z "$PROJECT_ROOT" ]]; then
  PROJECT_ROOT="$SCRIPT_DIR"
fi
if [[ -z "$OUT_DIR" ]]; then
  OUT_DIR="$PROJECT_ROOT/out"
fi
if [[ -z "$STATE_DIR" ]]; then
  STATE_DIR="/var/lib/reality-autorotate"
fi
if [[ -z "$MARZBAN_URL" ]]; then
  MARZBAN_URL="http://127.0.0.1:27500"
fi
if [[ -z "$XRAY_INBOUND_TAG" ]]; then
  XRAY_INBOUND_TAG="VLESS_REALITY"
fi

# Root check: in non-interactive mode allow non-root if all targets are not system paths.
if [[ "$NON_INTERACTIVE" -eq 0 ]]; then
  if [[ "${EUID}" -ne 0 ]]; then
    echo "ERROR: please run as root: sudo bash install.sh" >&2
    exit 2
  fi
else
  if [[ "${EUID}" -ne 0 ]]; then
    # allow if not touching /etc or /etc/systemd
    if [[ "$ENV_FILE" == /etc/* || "$SYSTEMD_DIR" == /etc/* ]]; then
      echo "ERROR: non-interactive mode with system paths requires root" >&2
      exit 2
    fi
  fi
fi

# Validate
[[ -d "$PROJECT_ROOT" ]] || { echo "ERROR: PROJECT_ROOT not found: $PROJECT_ROOT" >&2; exit 2; }
validate_state_dir "$STATE_DIR" || exit 2

prompt_default() {
  local question="$1" default_value="$2" value=""
  read -r -p "${question} [${default_value}]: " value || true
  value="${value%%$'\r'}"
  value="${value%%$'\n'}"
  if [[ -z "$value" ]]; then
    printf '%s' "$default_value"
  else
    printf '%s' "$value"
  fi
}

prompt_secret() {
  local question="$1" default_value="$2" value=""
  # If stdin is not a TTY (e.g. tests/heredoc), avoid -s to not break reads.
  if [[ -t 0 ]]; then
    read -r -s -p "${question} [hidden]: " value || true
    echo >&2
  else
    read -r value || true
  fi

  value="${value%%$'\r'}"
  value="${value%%$'\n'}"

  if [[ -z "$value" ]]; then
    printf '%s' "$default_value"
  else
    printf '%s' "$value"
  fi
}

yes_no() {
  local question="$1" default_value="$2" answer=""
  read -r -p "${question} (y/n) [${default_value}]: " answer || true
  answer="${answer%%$'\r'}"
  answer="${answer%%$'\n'}"
  if [[ -z "$answer" ]]; then
    answer="$default_value"
  fi
  case "${answer,,}" in
    y|yes) return 0 ;;
    *) return 1 ;;
  esac
}

if [[ "$NON_INTERACTIVE" -eq 0 ]]; then
  echo "Realityscanner installer (VPS + OpenWrt artifacts)"
  echo "Supported: Ubuntu/Debian with systemd. Run as root."
  echo ""

  PROJECT_ROOT="$(prompt_default "PROJECT_ROOT (where this repo is located)" "$PROJECT_ROOT")"
  STATE_DIR="$(prompt_default "STATE_DIR (autorotate state dir)" "$STATE_DIR")"
  MARZBAN_URL="$(prompt_default "MARZBAN_URL (local Marzban API)" "$MARZBAN_URL")"
  XRAY_INBOUND_TAG="$(prompt_default "XRAY_INBOUND_TAG" "$XRAY_INBOUND_TAG")"
  MARZBAN_USER="$(prompt_default "MARZBAN_USER (Marzban admin login from Web UI)" "$MARZBAN_USER")"
  # In TTY prompt we do hidden input; in heredoc tests it's a normal line read.
  MARZBAN_PASS="$(prompt_secret "MARZBAN_PASS (Marzban admin password)" "$MARZBAN_PASS")"

  if yes_no "Enable Telegram notifications?" "n"; then
    TG_TOKEN="$(prompt_secret "TG_TOKEN" "$TG_TOKEN")"
    TG_ID="$(prompt_default "TG_ID" "$TG_ID")"
  else
    TG_TOKEN=""
    TG_ID=""
  fi

  if yes_no "Prepare OpenWrt files (no SSH; you will copy manually)?" "y"; then
    SUB_URL="$(prompt_default "SUB_URL (https://sub.example.com/sub/<token>)" "$SUB_URL")"
  else
    SUB_URL=""
  fi

  if yes_no "Prepare scanner now (managed run; requires git+go)?" "n"; then
    PREPARE_SCANNER=1
  else
    PREPARE_SCANNER=0
  fi

  echo ""
  echo "Will write: $ENV_FILE"
  echo "Will install units into: $SYSTEMD_DIR"
  echo "Will generate OpenWrt artifacts into: $OUT_DIR/openwrt"
  echo ""

  if [[ -f "$ENV_FILE" ]]; then
    if ! yes_no "Env file already exists. Overwrite?" "n"; then
      echo "Aborted." >&2
      exit 1
    fi
  fi

  if ! yes_no "Proceed with installation?" "y"; then
    echo "Aborted." >&2
    exit 1
  fi
else
  PREPARE_SCANNER=0
fi

# Validate again after interactive edits
[[ -d "$PROJECT_ROOT" ]] || { echo "ERROR: PROJECT_ROOT not found: $PROJECT_ROOT" >&2; exit 2; }
validate_state_dir "$STATE_DIR" || exit 2

if [[ "$NON_INTERACTIVE" -eq 1 ]]; then
  require_nonempty "MARZBAN_USER" "$MARZBAN_USER" || exit 2
  require_nonempty "MARZBAN_PASS" "$MARZBAN_PASS" || exit 2
else
  require_nonempty "MARZBAN_USER" "$MARZBAN_USER" || exit 2
  require_nonempty "MARZBAN_PASS" "$MARZBAN_PASS" || exit 2
fi

if [[ "${PREPARE_SCANNER:-0}" -eq 1 ]]; then
  # Best-effort: do not fail install if scanner prep fails; print guidance.
  if [[ -x "$PROJECT_ROOT/reality-realtlscanner-pipeline.sh" ]]; then
    echo "Preparing scanner (managed)... this may take a while" >&2
    set +e
    bash "$PROJECT_ROOT/reality-realtlscanner-pipeline.sh" </dev/null >/dev/null 2>&1
    prep_rc=$?
    set -e
    if [[ "$prep_rc" -ne 0 ]]; then
      echo "WARN: scanner preparation failed (rc=$prep_rc). You may need to run reality-realtlscanner-pipeline.sh manually." >&2
    fi
  else
    echo "WARN: scanner pipeline script not found/executable: $PROJECT_ROOT/reality-realtlscanner-pipeline.sh" >&2
  fi
fi

# Actions
write_env_file "$ENV_FILE"
copy_units "$SYSTEMD_DIR"
generate_openwrt_out "$OUT_DIR"

if [[ "$SKIP_SYSTEMD_ENABLE" -eq 0 ]]; then
  "$SYSTEMCTL_BIN" daemon-reload
  "$SYSTEMCTL_BIN" enable --now reality-autorotate-watchdog.timer
fi

if [[ "$NON_INTERACTIVE" -eq 0 ]]; then
  cat <<EOF

Installed.

1) VPS
- Env:   $ENV_FILE
- Units: $SYSTEMD_DIR/reality-autorotate-*.service + timer
- Timer enabled: reality-autorotate-watchdog.timer

2) OpenWrt (no SSH)
- Files prepared in: $OUT_DIR/openwrt/
  - podkop-sub-sync.sh
  - podkop-sub-sync.conf
  - INSTALL_OPENWRT.txt

Next (recommended):
  set -a; . "$ENV_FILE"; set +a
  "$PROJECT_ROOT/autorotate/bin/rotate.sh" --trigger manual --dry-run

EOF
fi
